language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME.m2/repository'
    - '$HOME.gradle'

script: "./backend_springboot/gradlew -p ./backend_springboot -x test clean build"

before_deploy:
  - zip -r myourcar ./backend_springboot
  - mkdir -p deploy
  - mv myourcar.zip deploy/myourcar.zip
  
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: myourcar-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
    
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: myourcar-build
    key: myourcar.zip
    bundle_type: zip
    application: myourcar
    deployment_group: myourcar-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - jinipyung@gmail.com
